name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python-version: "3.7", tox: py37}
          - {python-version: "3.8", tox: py38}
          - {python-version: "3.9", tox: py39}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip and setuptools
      run: |
        python -m pip install -U pip setuptools
    - name: Install tox
      run: pip install tox
    - name: Tests
      run: tox -e ${{ matrix.tox }}
    - name: Lints
      run: tox -e lint
